[package]
name = "birthday"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.76"
clap = { version = "4.4", features = ["derive"] }
rusqlite = { version = "0.30", features = ["bundled"] }
